Add in IRIDA Next updates and work towards best practices
phac-nml/legiovue pull request #7
Opened 2024-12-23 21:21 UTC by DarianHole

## Added
- nf-schema plugin
- iridanext plugin
- Skip param for plots
  - There is an apptainer/container incompatibility to solve at some point
- Test configs (no data yet so they will just fail)

## Adjusted
- Logic for input data
- Help, version, and param info to be nf-schema based
- El_Gato allele plots will skip if they error

## Issues Addressed
- Solves #5  
- Solves #6

2025-01-15 21:10 UTC, apetkau requested changes
This is amazing work. Thanks so much Darian 😄 . You've done a great job with this.

I have some in-line comments for you. Some of these are more meant for later PRs, or just recommendations or comments for your information for later. Please let me know if you have any questions.

2025-01-15 21:10 UTC, apetkau commented on nextflow_schema.json
> +                    "minimum": 1,
Is there a reason why these aren't `0` and `100`?

2025-01-15 21:10 UTC, apetkau commented on nextflow_schema.json
> +                    "default": "data/C9_S.reference.fna",
Is a reference for quast in your pipeline strictly required?

For integration with IRIDA Next, I'd recommend marking this as `"hidden": true` so it doesn't show up in the IRIDA Next UI if it's not required.

2025-01-15 21:10 UTC, apetkau commented on nextflow_schema.json
> +                    "default": "data/SeqSphere_1521_schema",
This can be for later, but I would recommend a bit of change in logic here for integration with IRIDA Next. Specifically, I'd recommend leaving this to a default of empty and in the pipeline, if empty, using the default `data/SeqSphere_1521_schema` that comes with the pipeline code.

That way, in IRIDA Next, we can always override it later on if it needs to be updated, but otherwise will default to the database distributed with the pipeline.

2025-01-15 21:10 UTC, apetkau commented on nextflow_schema.json
> +                    "type": "string",
I'd recommend marking these all as `"hidden": true` so they don't show up in IRIDA Next. We configure resource settings behind-the-scenes for IRIDA Next.

2025-01-15 21:10 UTC, apetkau commented on tests/main.nf.test
> +    test("Conflicting Input Data Sources Specified") {
Thanks so much for including a test for failure 😄

2025-01-15 21:10 UTC, apetkau commented on tests/main.nf.test
> +    test("Stub Run Test") {
Thanks so much for including this test 😄 

In general, I recommend not using stub runs for testing, but instead creating very small inputs and databases and running the full pipeline including all underlying dependency software.

However, doing that all requires time. This is a good first step and later on a full test can be added in here.

2025-01-16 13:38 UTC, apetkau commented on modules/local/bracken.nf
> +    when:
As discussed offline, switching some of these modules to the `modules/nf-core/` versions is something to make a note of, but is a lower priority so can be re-visited later.

2025-01-16 17:01 UTC, emarinier commented on modules/local/reportree.nf
> +// TODO - Incorporate when we have a time to create a working container/setup
Generally I recommend leaving TODOs out of main/dev and having them on GitHub as issues or whatever instead.

2025-01-16 17:02 UTC, emarinier commented on modules/local/spades.nf
> +    fi
I think Aaron mentioned this earlier, but there's an nf-core version of SPAdes that handles some of this stuff already.

2025-01-16 17:08 UTC, emarinier commented on nextflow_schema.json
> +                    "description": "Skip running all el_gato Sequence Typing aspects",
I think lowercase sequence typing unless the the el_gato name is exactly "el_gato Sequence Typing".

2025-01-16 17:09 UTC, emarinier commented on nextflow_schema.json
> +            "description": "Options for quast",
QUAST's name is all caps.

2025-01-16 17:09 UTC, emarinier commented on nextflow_schema.json
> +                    "description": "Path to reference fasta file to base quast metrics off of"
QUAST

2025-01-16 17:10 UTC, emarinier commented on nextflow_schema.json
> +            "title": "Chewbbaca options",
chewBBACA

2025-01-16 17:10 UTC, emarinier commented on nextflow_schema.json
> +            "description": "Options to specify the chewbbaca schema to use",
chewBBACA

2025-01-16 17:10 UTC, emarinier commented on nextflow_schema.json
> +                    "description": "Chewbbaca prepped schema",
chewBBACA

2025-01-16 17:11 UTC, emarinier commented on nextflow_schema.json
> +            "description": "Options to specify the chewbbaca schema to use",
Also consider rewriting for brevity:

"Specifies the chewBBACA schema."

2025-01-16 17:19 UTC, emarinier commented on tests/main.nf.test
> +    test("Stub Run Test") {
Yeah, echoing this. Testing the stub run only tests that the stub part works, not that the pipeline works under normal circumstances.

2025-01-16 17:22 UTC, emarinier commented on workflows/legiovue.nf
> +    ch_el_gato_report = Channel.value([])
I'd have to think about this more in context of the rest of the workflow, but creating an "empty" channel like this makes me wonder if there's another way of doing this?

2025-01-16 17:23 UTC, emarinier commented on workflows/legiovue.nf
> +    // 9. Clustering (TO-DO when environments available)
As before on TODOs. Just noting it.

2025-01-16 19:00 UTC, DarianHole commented on modules/local/bracken.nf
> +    task.ext.when == null || task.ext.when
Its in every single nf-core module but I just added it as the lint tests were complaining it didn't exist in the local modules. I'm not 100% sure why either

ex. https://github.com/nf-core/modules/blob/master/modules/nf-core/sratools/fasterqdump/main.nf#L19

2025-01-20 14:10 UTC, DarianHole commented on assets/schema_input.json
> +        "required": ["sample", "fastq_1", "fastq_2"]
Yeah only paired end data right now is allowed. Thanks for pointing it out as well :)

2025-01-20 14:11 UTC, DarianHole commented on bin/combine_qc_data.py
> +    elif outdict['num_paired_trimmed_reads'] < 150000:
I've set them all to be parameters that are in both nextflow and the python script now so hopefully that helps out

2025-01-20 14:12 UTC, DarianHole commented on nextflow_schema.json
> +                    "minimum": 1,
I feel like the schema builder page got mad at me for having it at 0 but I've adjusted it as your right it should be

2025-01-20 14:14 UTC, DarianHole commented on tests/main.nf.test
> +    test("Stub Run Test") {
Yeah I thought that it may be a good spot to put it as a test but makes sense not to. I've changed it to actual data

2025-01-20 14:17 UTC, DarianHole commented on README.md
> +This project serves as a repository for tools, notes, and informtation regarding the LegioVue pipeline. This project is a GRDI funded research project surrounding the **assessment and implementation
I adjusted it to "This project serves as a repository for the LegioVue analysis pipeline along with validation notes and information on follow-up data analysis steps like clustering" which I think better captures what we want to use the repo for

2025-01-20 14:18 UTC, DarianHole commented on bin/quast_analyzer.py
> +def calculate_score(metric: int, bottom=80000, top=220000):
Yeah that is very true, thanks for pointing it out, I've added in parameters for both to make them adjustable

2025-01-20 14:19 UTC, DarianHole commented on conf/modules.config
> +            path: { "${params.outdir}/el_gato/plots" },
Yep! I adjusted the process name as well to make it easier to see where its involved

2025-01-20 14:23 UTC, DarianHole commented on conf/modules.config
> +            path: { "${params.outdir}" },
Yep, I adjusted the process name to make it easier to know at a glance what it does

2025-01-20 14:23 UTC, DarianHole commented on docs/roadmap.md
>  # Development Roadmap
Removed

2025-01-20 14:25 UTC, DarianHole commented on modules/local/plotting.nf
> +    label 'error_ignore'
It was container related usually (something odd with versions of docker and singularity. I've switched to a better container and no longer need it

2025-01-20 14:26 UTC, DarianHole commented on modules/local/reportree.nf
> +// TODO - Incorporate when we have a time to create a working container/setup
I've removed the reportree modules for now and add them as issues, good point

2025-01-20 14:29 UTC, DarianHole commented on workflows/legiovue.nf
> +    ch_el_gato_report = Channel.value([])
I'm not sure. I have it to allow someone to skip the sequence typing steps if that is not something they need. I followed the convention I saw in other pipelines to do it when the output of the steps is used later for reporting

Ex. https://github.com/nf-core/viralrecon/blob/master/workflows/nanopore.nf#L387

2025-01-20 15:12 UTC, DarianHole commented on main.nf
> +    log.error "Please provide input data with either: '--input input.csv' or '--fastq_dir <PATH/TO/PAIRED_FASTQS>' but not both"
Yeah nf-core requires `--input` and it'll allow IRIDA Next to interface with the pipeline from my understanding. The directory input option is more for other uses as an additional way to get data into the pipeline that some may find more friendly than the creation of a samplesheet

2025-01-22 19:56 UTC, emarinier approved these changes

2025-01-23 15:33 UTC, merged